# Data Processing

In [16]:
import pandas as pd
import numpy as np


## Defining features and dependent variables

In [17]:
# Importing the dataset
dataset = pd.read_csv('./Data.csv')

# Features (independent variables)
# iloc -> locate indexes, @first param: rows, @second param: columns
# getting the first 3 columns
# : means range in python and its include the lower bound but not the upper bound
# empty range (:) = include everything 
features = dataset.iloc[:, :-1].values # all the rows and all the columns ixcluding the last one

# getting the last column
dependent_variable = dataset.iloc[:, -1]


## Dealing with messing data

In [18]:
# Dealing of missing data

from sklearn.impute import SimpleImputer

# replace all the missing values in the value by the mean (np.nan = NAN / no value)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# fit just work for numerical values
# search all the missing values from all rowas and second and third column (age and salary)
imputer.fit(features[:, 1:3])
features[:, 1:3] = imputer.transform(features[:, 1:3])

print(features)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Enconding categorical data

In [19]:
# Encoding categorical data

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# 0 => because we need to encode the first column "country"
# passthrough => to keep all the columns after the transformation
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# apply the transformation
features = np.array(ct.fit_transform(features))

print(features)



[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Enconding the dependent variable

In [20]:
# Encoding the dependent variable

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

dependent_variable = le.fit_transform(dependent_variable)

print(dependent_variable)


[0 1 0 0 1 1 0 1 0 1]


## Spliting the dataset into training and test set

In [21]:
from sklearn.model_selection import train_test_split

f_train, f_test, dv_train, dv_test = train_test_split(features, dependent_variable, test_size=0.2, train_size=0.8, random_state=1)


## Feature scaling

In [22]:
# we dont apply feature scaling to the encoding data (for example the binaries in categorical variables)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# all the columns after column 3, since the first 3 are always for encoding
# fit and transform applying the standardisation formula
f_train[:, 3:] = sc.fit_transform(f_train[:, 3:])

# the transform method applies the scaling using the previously computed mean and standard deviation
f_test[:, 3:] = sc.transform(f_test[:, 3:])

print(f_train)
print(f_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
